# Database example - system service with strict security
name: postgres
image: postgres:15
type: system

ports:
  postgres:
    container: 5432
    host: 5432

storage:
  persistent:
    data:
      container: /var/lib/postgresql/data
      size_limit: 20GB

environment:
  POSTGRES_DB: piccolo
  POSTGRES_USER: piccolo
  POSTGRES_PASSWORD: changeme

permissions:
  network:
    internet: deny        # No internet access for security
    local_network: allow  # Only local Piccolo network
  preset: database

resources:
  limits:
    memory: 2GB
    cpu: 1.0